#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"
echo ${HERE}
export LD_LIBRARY_PATH="$HERE/usr/lib"
export PYTHONHOME="$HERE/usr"
export QT_QPA_PLATFORM_PLUGIN_PATH="$HERE/usr/plugins/platforms"
export FONTCONFIG_PATH="$HERE/usr/etc/fonts"
${HERE}/usr/bin/FreeCAD
